stages:
  - deploy
  - publish

variables:
  DEPENDENCIES: findutils git libxslt python3-pip python3-lxml rubygem-jekyll yelp-tools yelp-xsl

pages:
  stage: deploy
  image: fedora:33
  script:
    - dnf install -y $DEPENDENCIES
    - jekyll build -d public/
    - git checkout main
    - mkdir public/help/
    - yelp-build html -o public/help help/C
  artifacts:
    paths:
      - public
  only:
    - pages

cloudflareworkers:
  stage: publish
  image: node:18-alpine
  script:
    - npm install -g wrangler
    - npm install workers-site/
    - npx wrangler deploy --env production
    - npx wrangler deploy --env oldproduction
  only:
    - pages
